### PR TITLE
Updates for Grails 2.4

### PR DESCRIPTION
**Pull request by rohitkumbhar**
Hi, 
This pull request contains all the previous changes plus changed need to work with Grails 2.4. These changes  will not work with Grails 2.3

### CODE REVIEW

**Comment by zimyx** [comment]
please,  now  nimble plugin   support  grails3.0  ?   how to do it

**Comment by fedecarossino** [comment]
hi, when you are going to merge this?

**Comment by snimavat** [comment]
@fedecarossino i will spend some time this week or next weeked and get it working with grails 2.4/2.5

@zimyx Nimble is not upgraded to grails 3 yet, are you already using nimble with older verion of grails ?

**Comment by zimyx** [comment]
I like nimble ,I want try website built on grails3.0

**Comment by snimavat** [comment]
@zimyx - as of now, nimble doesnt support grails 3, I am planning to upgrade it, but does not have a fixed timeline.

**Pull request closed without merging**
